# curl -X 'GET' 
#  'https://localhost:5001/Feeds?name=Gary%20Woodfine' 
#  -H 'accept: text/plain'
GET {{host}}/{{feeds_resource_name}}?name=Decrypt
accept: text/plain

> ../../Asserts/Feeds/Should_be_200_with_result.js

###


POST {{host}}/{{feeds_resource_name}}/:update/{{feeds_identifier}}
accept: */*

