### POST Website test
POST {{host}}/{{websites_resource_name}}
accept: application/json
Content-Type: application/json

{
  "feed": {
    "name": "Gary Woodfine - Opinionated Software Developer",
    "domain": "garywoodfine.com",
    "url": "/feed",
    "protocol" : "https"
  }
}

> ../../Asserts/Websites/Should_be_201_with_id.js

###

### POST Website test
POST {{host}}/{{websites_resource_name}}
accept: application/json
Content-Type: application/json

{
  "feed": {
    "name": "Crypto News: Latest Cryptocurrency News, Bitcoin News, Ethereum News and Price Data",
    "domain": "cryptonews.com",
    "url": "/news/feed",
    "protocol" : "https"
  }
}

> ../../Asserts/Websites/Should_be_201_with_id.js

###
### POST Website test
POST {{host}}/{{websites_resource_name}}
accept: application/json
Content-Type: application/json

{
  "feed": {
    "name": "Bitcoin Magazine - Bitcoin News, Articles and Expert Insights",
    "domain": "bitcoinmagazine.com",
    "url": "/.rss/full/",
    "protocol" : "https"
  }
}

> ../../Asserts/Websites/Should_be_201_with_id.js

###

### POST Website test
POST {{host}}/{{websites_resource_name}}
accept: application/json
Content-Type: application/json

{
  "feed": {
    "name": "Coin Telegraph - Bitcoin, Ethereum, Crypto News & Price Indexes",
    "domain": "cointelegraph.com",
    "url": "/rss",
    "protocol" : "https"
  }
}

> ../../Asserts/Websites/Should_be_201_with_id.js

###

https://cointelegraph.com/rss-feeds