### POST Website test
POST {{host}}/{{websites_resource_name}}
accept: application/json
Content-Type: application/json

{
  "feed": {
    "name": "Test Site {{$randomInt}}",
    "domain": "test{{$randomInt}}.com",
    "url": "/test/feed.xml",
    "protocol" : "https"
  }
}

> ../../Asserts/Websites/Should_be_201_with_id.js

###

### GET Website Tests
GET {{host}}/{{websites_resource_name}}
accept: application/json
Content-Type: application/json

> ../../Asserts/Should_be_200_Ok.js
###

### PUT website test 
PUT {{host}}/{{websites_resource_name}}/{{website_created_id}}
accept: */*
Content-Type: application/json

{
  "name": "put test {{$randomInt}}",
  "domain": "puttest{{$randomInt}}.com",
  "url": "/feed/feed.xml",
  "protocol": "https"
}

###

### PATCH Website test
PATCH {{host}}/{{websites_resource_name}}/{{website_created_id}}
accept: text/plain
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "value": "patch {{$randomInt}} test",
    "path": "name"
  }
]

> ../../Asserts/Should_be_200_Ok.js

###